export const projects = [
  {
    id: 1,
    title: "WorkflowAI",
    desc: "DoWell WorkflowAI recommends process optimisation for your task and manages it based on location and time",
    link: "https://ll04-finance-dowell.github.io/workflowai.online/",
    image: "/workflowAI.png",
    category: "contributions",
  },
  {
    id: 2,
    title: "Scales",
    desc: "Living Lab Scales measure quantitative data statistically.",
    link: "https://100035.pythonanywhere.com/client/",
    image: "/scales.png",
    category: "contributions",
  },
  {
    id: 3,
    title: "Team management",
    desc: "DoWell Team Management helps HR in recruiting and managing the team.",
    link: "https://ll07-team-dowell.github.io/100098-DowellJobPortal/#/",
    image: "/task.png",
    category: "contributions",
  },
  {
    id: 4,
    title: "Live Stream",
    desc: "DoWell Live Stream Dashboard helps record meetings on youtube publicly or privately.",
    link: "https://liveuxstoryboard.com/",
    image: "/live.png",
    category: "contributions",
  },
  {
    id: 5,
    title: "Dowell Services",
    desc: "DoWell Services is used to apply rate limiting to the different applications based on subscription status",
    link: "https://ll05-ai-dowell.github.io/100105-DowellApiKeySystem/#",
    image: "/services.png",
    category: "contributions",
  },
  {
    id: 6,
    title: "Infi Health template",
    desc: "Static websites with good looking UI to enhance my design and front end development skills",
    link: "https://doctor-mary.netlify.app/",
    image: "/services.png",
    category: "designs",
  },
  {
    id: 7,
    title: "Calendly clone",
    desc: "Static websites with good looking UI to enhance my design and front end development skills",
    link: "https://calendly.netlify.app/",
    image: "/services.png",
    category: "designs",
  },
  {
    id: 8,
    title: "Mental awareness template",
    desc: "Static websites with good looking UI to enhance my design and front end development skills",
    link: "https://mental-wellness.netlify.app/",
    image: "/services.png",
    category: "designs",
  },
  {
    id: 9,
    title: "Chat App",
    desc: "Chat application that enables users to interact based on their geographical location",
    link: "https://geochat1.netlify.app/login",
    image: "/chat.png",
    category: "websites",
  },
  {
    id: 10,
    title: "Portfolio",
    desc: "Static websites with good looking UI to enhance my design and front end development skills",
    link: "https://ndoneambrose.netlify.app/",
    image: "/portfolio.png",
    category: "websites",
  },
  {
    id: 11,
    title: "Ecommerce ",
    desc: "Ecommerce for non-profit metabolomics core facility at the University of Alberta in Edmonton, Canada",
    link: "https://www.tmicwishartnode.ca/",
    image: "/commerce.png",
    category: "websites",
  },
  {
    id: 12,
    title: "PDF Editor ",
    desc: "PDF editor with the ability to customize pdfs and create annotations as well as save/download the edited PDF",
    link: "https://pdf-editor-ambro.netlify.app/",
    image: "/pdf.png",
    category: "websites",
  },
];
